name: Deploy Using Actions Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ram-demos/cf-cli-action@master
      with:
        cf_api: https://api.34.70.72.42.xip.io
        cf_username: ${{ secrets.CF_ADMIN_EMAIL }}
        cf_password: ${{ secrets.CF_ACCESS_PASSWORD }}
        cf_org: livestream
        cf_space: ram
        command: push
